### ISSUE TITLE
No implementation found error. got flutter secure storage

### ISSUE THREAD

**Issue by bernardcraddock** [meta-flutter/workspace-automation#23]
@jwinarske

if I build workspace automation as follows then run ped -b agl - (includes secure storage) I get the follow No implementation found error.

However, if I switch to my -b ivi_localstore (doesn't include secure storage) everything works fine.
Are you able to advise what needs to be done either your end or mine to enable secure storage in desktop-homescreen working?

regards

git clone https://github.com/meta-flutter/workspace-automation -b main
./flutter_workspace.py --clean --flutter-version=3.16.4
source ./setup_env.sh
cd ped
flutter run -d desktop-homescreen 

Resolving dependencies... (1.3s)
  _fe_analyzer_shared 64.0.0 (65.0.0 available)
  analyzer 6.2.0 (6.3.0 available)
  coverage 1.6.4 (1.7.2 available)
  file 6.1.4 (7.0.0 available)
  fl_chart 0.64.0 (0.65.0 available)
+ flutter_secure_storage 9.0.0
+ flutter_secure_storage_linux 1.2.0
+ flutter_secure_storage_macos 3.0.1
+ flutter_secure_storage_platform_interface 1.0.2
+ flutter_secure_storage_web 1.1.2
+ flutter_secure_storage_windows 3.0.0
  intl 0.18.1 (0.19.0 available)
  matcher 0.12.16 (0.12.16+1 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.10.0 (1.11.0 available)
  path 1.8.3 (1.9.0 available)
  platform 3.1.2 (3.1.3 available)
  process 4.2.4 (5.0.1 available)
  test 1.24.9 (1.25.0 available)
  test_api 0.6.1 (0.7.0 available)
  test_core 0.5.9 (0.6.0 available)
  uuid 4.2.2 (4.3.1 available)
  vm_service 11.10.0 (14.0.0 available)
  web 0.3.0 (0.4.0 available)
  web_socket_channel 2.4.0 (2.4.1 available)
  webdriver 3.0.2 (3.0.3 available)
Changed 6 dependencies!
20 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on Toyota homescreen in debug mode...
[21:04:17.560593] [I] main @ 5ab78a1
[21:04:17.560661] [I] **********
[21:04:17.560671] [I] * Global *
[21:04:17.560678] [I] **********
[21:04:17.560686] [I] Application Id: .......... homescreen
[21:04:17.560694] [I] JSON Configuration: ...... .desktop-homescreen/default_config.json
[21:04:17.560701] [I] Disable Cursor: .......... false
[21:04:17.560709] [I] Debug Backend: ........... false
[21:04:17.560719] [I] ********
[21:04:17.560749] [I] * View *
[21:04:17.560758] [I] ********
[21:04:17.560765] [I] Bundle Path: .............. .desktop-homescreen
[21:04:17.560776] [I] Window Type: .............. NORMAL
[21:04:17.560785] [I] Output Index: ............. 0
[21:04:17.560793] [I] Size: ..................... 1920 x 1080
[21:04:17.560804] [I] Fullscreen: ............... false
[21:04:17.560814] [I] Accessibility Features: ... 0
[21:04:17.608955] [I] Pointer Present
[21:04:17.609005] [I] Keyboard Present
[21:04:17.680445] [I] (0) Runtime=debug
[21:04:17.944034] [E] Not sending message on Platform Thread
[21:04:17.979163] [E] Not sending message on Platform Thread
[21:04:18.001347] [E] Not sending message on Platform Thread
[21:04:18.032530] [I] Channel: "plugins.it_nomads.com/flutter_secure_storage"
0x000000: 07 04 72 65 61 64 0d 02 07 03 6b 65 79 07 24 70  ..read....key.$p
0x000010: 65 64 5f 75 69 5f 73 65 74 74 69 6e 67 73 5f 63  ed_ui_settings_c
0x000020: 6f 6c 6c 2d 70 65 64 5f 75 69 5f 73 65 74 74 69  oll-ped_ui_setti
0x000030: 6e 67 73 07 07 6f 70 74 69 6f 6e 73 0d 00        ngs..options..

[21:04:18.032559] [E] Not sending message on Platform Thread
[21:04:18.034360] [I] [2023-12-20 21:04:18.025565]: DEBUG: UiSettingsDao : Retrieving instance of UiSettings
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
<asynchronous suspension>
#1      SecureStorage.readData (package:pumped_end_device/data/local/dao2/secure_storage.dart:42:12)
<asynchronous suspension>
#2      UiSettingsDao.getUiSettings (package:pumped_end_device/data/local/dao2/ui_settings_dao.dart:41:26)
<asynchronous suspension>
#3      main (package:pumped_end_device/main.dart:50:28)
<asynchronous suspension>

Syncing files to device Toyota homescreen...                       113ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Toyota homescreen is available at: http://127.0.0.1:43797/lOlPgAGMShU=/
The Flutter DevTools debugger and profiler on Toyota homescreen is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:43797/lOlPgAGMShU=/

**Comment by bernardcraddock** [comment]
Closed as missing  libsecret-devel package
