### ISSUE TITLE
E: Unable to locate package vulkan-utils

### ISSUE THREAD

**Issue by bernardcraddock** [meta-flutter/workspace-automation#9]
@jwinarske 

I previously informed you i had to install following vulkan packages to get it workspace-automation building 
"vulkan. - sudo apt install libvulkan-dev vulkan-tools vulkan-validationlayers vulkan-utils"

However directly after pulling your May 31st commit i started receiving  E: Unable to locate package vulkan-utils, so not sure if one of your changes caused this or (perhaps more likely) I had been over zealous requesting vulkan-utils and its not required.

You inserted following
line 55 configs/desktop-auto.json
"sudo apt install -y build-essential libvulkan-dev vulkan-tools vulkan-validationlayers vulkan-utils libtool",

Soon as i removed vulkan-utils it started working again, so you may want to do make the change
"sudo apt install -y build-essential libvulkan-dev vulkan-tools vulkan-validationlayers libtool",

E: Unable to locate package vulkan-utils
Traceback (most recent call last):
  File "/home/parallels/Documents/GitHub/workspace-automation/./flutter_workspace.py", line 2465, in <module>
    main()
  File "/home/parallels/Documents/GitHub/workspace-automation/./flutter_workspace.py", line 300, in main
    setup_platforms(platforms, github_token, cookie_file, args.plex)
  File "/home/parallels/Documents/GitHub/workspace-automation/./flutter_workspace.py", line 1866, in setup_platforms
    setup_platform(platform_, git_token, cookie_file, plex)
  File "/home/parallels/Documents/GitHub/workspace-automation/./flutter_workspace.py", line 1845, in setup_platform
    handle_pre_requisites(runtime.get('pre-requisites'), cwd)
  File "/home/parallels/Documents/GitHub/workspace-automation/./flutter_workspace.py", line 1289, in handle_pre_requisites
    handle_commands(distro.get('cmds'), cwd)
  File "/home/parallels/Documents/GitHub/workspace-automation/./flutter_workspace.py", line 1534, in handle_commands
    subprocess.check_call(cmd_arr, cwd=cwd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', 'apt', 'install', '-y', 'build-essential', 'libvulkan-dev', 'vulkan-tools', 'vulkan-validationlayers', 'vulkan-utils', 'libtool']' returned non-zero exit status 100.

regards

**Comment by jwinarske** [comment]
@bernardcraddock Hi Bernard.  Thanks for the issue report.  I just pushed a change to main which most likely addresses your problem.  It was failing to detect packages on Ubuntu.  It now properly detects them.  Not sure when that snuck in, but should be good to go now.  Let me know.  Thanks again.

**Comment by jwinarske** [comment]
Closing since this has been resolved

**Comment by payam-zahedi** [comment]
I have the same issue 
I'm running it on ubuntu 22.04 on a virtual box
